### ISSUE TITLE
Win 8.1 Install Failure

### ISSUE THREAD

**Issue by Robzilla** [0xcert/ethereum-xcert#29]
Hi all

Firstly you might want to say somewhere on the readme that Python 2 (not 3) is a requirement.
Currently failing on the install command with the following error.

D:\Dev\GitHub\ethereum-xcert>npm install

> sha3@1.2.2 install D:\Dev\GitHub\ethereum-xcert\node_modules\sha3
> node-gyp rebuild

D:\Dev\GitHub\ethereum-xcert\node_modules\sha3>if not defined npm_config_node_gyp (node "C:\Users\hollambyro\AppData\Roa
ming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
)  else (node "C:\Users\hollambyro\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4025: The project file could not be loaded. Root element is missing.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\hollambyro\AppData\Roaming\npm\node_modules\npm\node_modules\node-gy
p\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hollambyro\\AppData\\Roaming\\npm\\node_modules\\npm\
\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Dev\GitHub\ethereum-xcert\node_modules\sha3
gyp ERR! node -v v10.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sha3@1.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hollambyro\AppData\Roaming\npm-cache\_logs\2018-05-31T02_23_22_432Z-debug.log

I have attached the full log

[2018-05-31T02_23_22_432Z-debug.log](https://github.com/0xcert/ethereum-xcert/files/2056377/2018-05-31T02_23_22_432Z-debug.log)

**Comment by leonpanjtar** [comment]
Hi @Robzilla,

Thanks for opening the issue, however this is not a Node, npm or repository issue. It is common to experience `node_gyp` problems on Windows development environments. I suggest you check out [this article](https://www.robertkehoe.com/2015/03/fix-node-gyp-rebuild-error-on-windows/) that explains how to set this up.

**Comment by xpepermint** [comment]
Closing this issue since it's not directly related to this project.
